package com.giusdp.htduels.presentation.ui;

import com.hypixel.hytale.codec.builder.BuilderCodec;
import com.hypixel.hytale.component.Ref;
import com.hypixel.hytale.component.Store;
import com.hypixel.hytale.protocol.packets.interface_.CustomPageLifetime;
import com.hypixel.hytale.server.core.Message;
import com.hypixel.hytale.server.core.entity.entities.player.pages.InteractiveCustomUIPage;
import com.hypixel.hytale.server.core.ui.builder.UICommandBuilder;
import com.hypixel.hytale.server.core.ui.builder.UIEventBuilder;
import com.hypixel.hytale.server.core.universe.PlayerRef;
import com.hypixel.hytale.server.core.universe.world.storage.EntityStore;

import javax.annotation.Nonnull;

// Generated by Hytale UI Builder (https://hytale.ellie.au).
// You may edit this class as necessary, or copy parts only.
public class BoardGameUi extends InteractiveCustomUIPage<BoardGameUi.BindingData> {

    public BoardGameUi(@Nonnull PlayerRef playerRef, @Nonnull CustomPageLifetime lifetime) {
        super(playerRef, lifetime, BindingData.CODEC);
    }

    @Override
    public void build(@Nonnull Ref<EntityStore> ref, @Nonnull UICommandBuilder uiCommandBuilder,
                      @Nonnull UIEventBuilder uiEventBuilder, @Nonnull Store<EntityStore> store) {
        uiCommandBuilder.append("Pages/BoardGame.ui");

        // var config = MyPlugin.getInstance().config.get();

    }

    public void updateTurnIndicator(String text) {
        UICommandBuilder commandBuilder = new UICommandBuilder();
        commandBuilder.set("#turnIndicator.Text", text);
        sendUpdate(commandBuilder, null, false);
    }

    @Override
    public void handleDataEvent(@Nonnull Ref<EntityStore> ref, @Nonnull Store<EntityStore> store,
                                @Nonnull BindingData data) {
        super.handleDataEvent(ref, store, data);
        boolean changed = false;

        if (changed) {
            this.playerRef.sendMessage(Message.raw("Changes processed."));
        }
    }

    public static class BindingData {
        public static final BuilderCodec<BindingData> CODEC = BuilderCodec.builder(BindingData.class, BindingData::new)

                .build();

    }
}
